### ISSUE TITLE
Choose theme

### ISSUE THREAD

**Issue by 1995parham** [AUT-SSC/aut-ceit.github.io#1]
Choose appropriate jekyll theme. we can start from [here](http://jekyllthemes.org/) and as we discussed before we can learn from [ssc of sharif ce website](http://ssc.ce.sharif.edu/).

**Comment by mahtabfarrokh** [comment]
i don't know what to choose but i liked these themes : 
http://jekyllthemes.org/themes/feeling-responsive/
http://jekyllthemes.org/themes/ion/

**Comment by pesehr** [comment]
why are we speaking English?

**Comment by 1995parham** [comment]
اینم حرفیست 😄
